### ISSUE TITLE
Request for Feedback on Attribution and Modifications for QRF Extrapolation Example

### ISSUE THREAD

**Issue by reidjohnson** [NiklasPfister/ExtrapolationAware-Inference#2]
Hello authors,

Thank you for your outstanding work and commitment to reproducibility. As the lead maintainer of the quantile-forest package, I was thrilled to see your experiments make use of it. I intend to feature a self-contained adaptation of your work as a prime example of extrapolation using quantile regression forests. You can view the proposed example [here](https://github.com/zillow/quantile-forest/pull/38) (to replace the current one [here](https://zillow.github.io/quantile-forest/gallery/plot_quantile_extrapolation.html)). Please let me know if you have any preferences regarding attribution or if you identify any corrections needed in my adaptation.

**Comment by NiklasPfister** [comment]
Hi Reid,

Happy to see the work being applied. I just took a quick look and your adaption looks fine to me. If I understood correctly you changed the rf weights in the local polynomial to qrf weights, is that correct? If so you should be aware that the derivative estimation is somewhat delicate (particularly in multi-dimensions) and we did have some trouble when not using the adapted linear regression splitting trees (in one-dimension what you do should be fine though).

Best,
Niklas

**Comment by reidjohnson** [comment]
Thanks so much for the feedback, Niklas. Your understanding is correct. I'll clearly document the limitations you've highlighted within the code and recommend users to refer to your original implementation for practical applications. Cheers.
